routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

  
Route::get('/', 'Auth\LoginController@ShowLoginForm')->middleware('guest');;


Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', function () {
        return view('administrator/dashboard/dashboard');  
    });
    
    Route::resource('/barang', 'barangController');
    Route::get('barang/tambah/stok', 'barangController@addStock')->name('add.stok');
    Route::post('barang/tambah/stok', 'barangController@storeStock')->name('barang.stok.store');
    Route::resource('/gudang', 'gudangController');
    Route::resource('/transaksi', 'transaksiController');
    Route::resource('/cart', 'CartController');
    Route::resource('/laporan', 'laporanController');
    Route::post('cart/add', 'CartController@add')->name('cart.add');
    Route::post('cart/remove', 'CartController@remove')->name('cart.remove');

    Route::get('/transaksi/print/{invoice}', 'transaksiController@generatePDF')->name('invoice.print');
    
    Route::get('/pelanggan', function () {
        return view('administrator/pelanggan');  
    });
});

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/barangController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\MonthlyStock;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\BarangStoreRequest;


class barangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $barangs = Product::paginate(10);

        return view('administrator.barang.index',compact('barangs'));
    }    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrator.barang.tambah');
    }
      
    /**
     * Store barang to database.
     *
     * @param \App\Http\Requests\BarangStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(BarangStoreRequest $request)
    {
        DB::transaction(function () use ($request) {
            /** @var \App\Product $barang */
            $het = str_replace('.', '', $request->het); 
            $buy_price = str_replace('.', '', $request->buy_price); 
            $barang = Product::create(
                    array_merge($request->validated(), ['het'=>$het, 'buy_price'=>$buy_price])
            );
            MonthlyStock::create([
                'product_id' => $barang->id,
                'stok' => $request->stok
            ]);

        });

        return redirect()->route('barang.index');
    }

            /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $barang)
    {
        return view('administrator.barang.edit', compact('barang'));
    }

            /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\BarangStoreRequest  $request
     * @param  \App\Barang $barang
     * @return \Illuminate\Http\Response
     */
    public function update(BarangStoreRequest $request, Product $barang)
    {
        DB::transaction(function () use ($barang, $request) {
            /** @var \App\Barang $barang */
            $het = str_replace('.', '', $request->het); 
            $buy_price = str_replace('.', '', $request->buy_price); 
            $barang->update(array_merge($request->validated(), ['het'=>$het, 'buy_price'=>$buy_price])
                    );
        });

        return redirect()->route('barang.index')->with('notification.success', trans('Barang berhasil di update.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $barang
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $barang)
    {
        $barang->delete();

        return redirect()->route('barang.index')->with('notification.success', trans('Barang berhasil di hapus.'));
    }

    public function addStock()
    {
        return view('administrator.barang.stok');
    }

    public function storeStock(Request $request)
    {
        $barang = Product::where('partnumber',$request->partnumber)->first();
        DB::transaction(function () use ($barang, $request) {
            /** @var \App\Barang $barang */
            $stok = $barang->stok + $request->tambah_stok;
            $barang->update(['stok'=> $stok
                        ]);
            MonthlyStock::create([
                'product_id' => $barang->id,
                'stok' => $request->tambah_stok
                ]);
            
        });

        return redirect()->route('barang.index')->with('notification.success', trans('Stok barang berhasil di tambah.'));
    }
    
}

resources/views/administrator/barang/edit.blade.php
@extends('administrator.header')

@section('isi')
<div class="container" style="padding-top:25px;">  
  <button class="btn btn-warning" onclick="history.back();"><i class="fa fa-arrow-left"></i> Kembali</button>  
  <form action="{{route('barang.update',$barang->id)}}" method="post">
      {{ csrf_field() }}
      {{ method_field('PUT') }}
        <div class="form-group">
        <label for="Part Number">Part Number</label>
        <input type="text" class="form-control" id="partnumber" name="partnumber" value="{{$barang->partnumber}}" required>
        </div>
        <div class="form-group">
        <label for="Description">Description</label>
        <input type="text" class="form-control" id="description" name="description" value="{{$barang->description}}" required>
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <label class="input-group-text" for="inputGroupSelect01">F/R</label>
            </div>
            <select class="custom-select" id="inputGroupSelect01" name="fr">
            <option selected hidden value="{{$barang->fr}}">{{$barang->fr}}</option>
              <option value="F">F</option>
              <option value="R">R</option>
            </select>
          </div>

          <div class="form-group">
            <label for="Pattern">Pattern</label>
            <input type="text" class="form-control" id="Pattern" name="pattern" value="{{$barang->pattern}}" required>
          </div>
          <div class="form-group">
            <label for="ukuran">Ukuran</label>
            <input type="text" class="form-control" id="ukuran" name="ukuran" value="{{$barang->ukuran}}" required>
          </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <label class="input-group-text" for="inputGroupSelect01">TL/TT</label>
            </div>
            <select class="custom-select" id="inputGroupSelect01" name="tltt">
              <option selected hidden value="{{$barang->tltt}}">{{$barang->tltt}}</option>
              <option value="TL">TL</option>
              <option value="TT">TT</option>
            </select>
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <label class="input-group-text" for="inputGroupSelect01">TYPE</label>
            </div>
            <select class="custom-select" id="inputGroupSelect01" name="type">
              <option selected hidden value="{{$barang->type}}">{{$barang->type}}</option>
              <option value="Radial">Radial</option>
              <option value="Radialino">Radialino</option>
            </select>
        </div>
        <div class="form-group">
          <label for="buy_price">Harga Beli</label>
          <input type="text" class="form-control mask-money" id="buy_price" name='buy_price' placeholder="RP..." value="{{number_format($barang->buy_price,0,',','.')}}">
        </div>
        <div class="form-group">
            <label for="het">HET</label>
            <input type="text" class="form-control mask-money" id="het" name='het' placeholder="RP..." value="{{number_format($barang->het,0,',','.')}}">
          </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Stok</label>
            <input type="number" class="form-control" id="stok" name='stok' placeholder="unit" value="{{$barang->stok}}">
        </div>

        <button type="submit" class="btn btn-primary">Simpan</button>
  </form>
</div>
@endsection
@push('script')
<script src="{{asset('js/jquery.maskMoney.min.js')}}"></script>
<script>
$(document).ready(function () {

     $('#het').maskMoney({thousands:'.', decimal:',', precision:0});
     $('#buy_price').maskMoney({thousands:'.', decimal:',', precision:0});
    
});
</script>
@endpush

resources/views/administrator/barang/flash-message.blade.php
@if(Session::has('notification.success'))
<div style="position:absolute; z-index: 10020; margin-top: 5px; right: 25px;">
  
    <div class="alert alert-success alert-dismissable fade show" role="alert">
        <i class="fas fa-lg fa-exclamation-circle mr-2"></i>
        {!! \Session::get('notification.success') !!}
        <button style="padding-left:10px" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>
 @endif

<script>
window.setTimeout(function() {
    $("div.alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 2500);
</script>

resources/views/administrator/barang/index.blade.php
@extends('administrator.header')
@section('isi')
@include('administrator.barang.flash-message')
<div class="container" style="padding-top:25px;">
    <div class="card">
        <div class="card-body">
          <h5 class="card-title">Barang
            <a href="{{route('add.stok')}}" style="margin-left:10px;" class="btn btn-primary btn-sm float-right">Tambah Stok</a>
            <a href="{{route('barang.create')}}" class="btn btn-primary btn-sm float-right">Tambah Barang</a>
          </h5>
          <table class="table table-striped table-bordered">
            <thead>
              <tr class="text-center">
                <th scope="col">Part Number</th>
                <th scope="col">Desc</th>
                <th scope="col">F/R</th>
                <th scope="col">TL/TT</th>
                <th scope="col">Pattern</th>
                <th scope="col">Ukuran</th>
                <th scope="col">Type</th>
                <th scope="col">Harga Beli</th>
                <th scope="col">HET</th>
                <th scope="col">STOK</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
              @foreach ($barangs as $bar)
              <tr>
                <td>{{$bar->partnumber}}</td>
                <td>{{$bar->description}}</td>
                <td>{{$bar->fr}}</td>
                <td>{{$bar->tltt}}</td>
                <td>{{$bar->pattern}}</td>
                <td>{{$bar->ukuran}}</td>
                <td>{{$bar->type}}</td>
                <td>{{number_format($bar->buy_price,0,',','.')}}</td>
                <td>{{number_format($bar->het,0,',','.')}}</td>
                <td>{{$bar->stok}}</td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                      <a role="button" href="{{ route('barang.edit', $bar->id) }}" class="btn btn-sm btn-icon text-muted" data-toggle="tooltip" title="Edit">
                        <i class="material-icons-outlined">edit</i>
                      </a>
                      <form action="{{ route('barang.destroy', $bar->id) }}" method="POST" class="d-inline" onsubmit="return confirm('Are you sure delete?');">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <button class="btn btn-sm btn-icon text-muted" data-toggle="tooltip" title="Delete">
                          <i class="material-icons-outlined">delete</i>
                      </button>
                      </form>
                    </div>
                </td>
              </tr>
              @endforeach
            </tbody>
            <tfoot>
              <tr>
                  <td colspan="100">{{ $barangs->links('administrator.pagination.pagination') }}</td>
              </tr>
          </tfoot>
          </table>
        </div>
      </div>
</div>
@endsection

resources/views/administrator/barang/stok.blade.php
@extends('administrator.header')

@section('isi')
<div class="container" style="padding-top:25px;padding-bottom:25px;">  
  <button class="btn btn-warning" onclick="history.back();"><i class="fa fa-arrow-left"></i> Kembali</button>  
  <form action="{{route('barang.stok.store')}}" method="post">
      {{ csrf_field() }}
        <div class="form-group">
        <label for="partnumber">Part Number</label>
        <input type="text" class="form-control" id="partnumber" name="partnumber" required>
        </div>
        <div id="detail" style="display:none;">
          <div class="form-group">
          <label for="pattern">Pattern</label>
          <input type="text" class="form-control" id="pattern" name="pattern" readonly>
          </div>

        <div class="form-group">
            <label for="sisa_stok"> Sisa Stok</label>
            <input type="number" class="form-control" id="sisa_stok" name='sisa_stok' min="1" placeholder="unit" readonly>
        </div>
      
        <div class="form-group">
            <label for="stok">Tambah Stok</label>
            <input type="number" class="form-control" id="tambah_stok" name='tambah_stok' min="1" placeholder="unit" required>
        </div>
        <button type="submit" class="btn btn-primary">Tambah</button>
        </div>
  </form>
</div>
@endsection

@push('css')
<link rel="stylesheet" href="{{ asset('css/easy-autocomplete.min.css') }}">
@endpush

@push('script')
<script src="{{asset('js/jquery.easy-autocomplete.min.js')}}"></script>
<script src="{{asset('js/jquery.maskMoney.min.js')}}"></script>
<script>
$(document).ready(function () {

     $('#het').maskMoney({thousands:'.', decimal:',', precision:0});
     $('#buy_price').maskMoney({thousands:'.', decimal:',', precision:0});
    
});
        $('#partnumber').easyAutocomplete({
            data: @json(App\Product::all()),
            getValue: 'partnumber',
            list: {
                match: { enabled: true },
                maxNumberOfElements: 5,
                onChooseEvent: function () {
                    $('#detail').show();
                    var selected = $('#partnumber').getSelectedItemData()
                    $('#partnumber').val(selected.partnumber);
                    $('#sisa_stok').val(selected.stok);
                    $('#pattern').val(selected.pattern);
                    
                }
            },
        });
</script>
@endpush

resources/views/administrator/barang/tambah.blade.php
@extends('administrator.header')

@section('isi')
<div class="container" style="padding-top:25px;padding-bottom:25px;">  
  <button class="btn btn-warning" onclick="history.back();"><i class="fa fa-arrow-left"></i> Kembali</button>  
  <form action="{{route('barang.store')}}" method="post">
      {{ csrf_field() }}
        <div class="form-group">
        <label for="partnumber">Part Number</label>
        <input type="text" class="form-control" id="partnumber" name="partnumber" required>
        </div>
        <div class="form-group">
        <label for="Description">Description</label>
        <input type="text" class="form-control" id="description" name="description" required>
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <label class="input-group-text" for="inputGroupSelect01">F/R</label>
            </div>
            <select class="custom-select" id="inputGroupSelect01" name="fr">
              <option selected>Pilih...</option>
              <option value="F">F</option>
              <option value="R">R</option>
            </select>
          </div>

          <div class="form-group">
            <label for="Pattern">Pattern</label>
            <input type="text" class="form-control" id="Pattern" name="pattern" required>
          </div>
          <div class="form-group">
            <label for="ukuran">Ukuran</label>
            <input type="text" class="form-control" id="ukuran" name="ukuran" required>
          </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <label class="input-group-text" for="inputGroupSelect01">TL/TT</label>
            </div>
            <select class="custom-select" id="inputGroupSelect01" name="tltt">
              <option selected>Pilih...</option>
              <option value="TL">TL</option>
              <option value="TT">TT</option>
            </select>
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <label class="input-group-text" for="inputGroupSelect01">TYPE</label>
            </div>
            <select class="custom-select" id="inputGroupSelect01" name="type">
              <option selected>Pilih...</option>
              <option value="Radial">Radial</option>
              <option value="Radialino">Radialino</option>
            </select>
        </div>
        <div class="form-group">
          <label for="buy_price">Harga Beli</label>
          <input type="text" class="form-control mask-money" id="buy_price" name='buy_price' placeholder="RP...">
        </div>
        <div class="form-group">
            <label for="het">HET</label>
            <input type="text" class="form-control mask-money" id="het" name='het' placeholder="RP...">
          </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Stok</label>
            <input type="number" class="form-control" id="stok" name='stok' min="1" placeholder="unit">
        </div>

        <button type="submit" class="btn btn-primary">Tambah</button>
  </form>
</div>
@endsection

@push('script')
<script src="{{asset('js/jquery.maskMoney.min.js')}}"></script>
<script>
$(document).ready(function () {

     $('#het').maskMoney({thousands:'.', decimal:',', precision:0});
     $('#buy_price').maskMoney({thousands:'.', decimal:',', precision:0});
    
});
</script>
@endpush