routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

  
Route::get('/', 'Auth\LoginController@ShowLoginForm')->middleware('guest');;


Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', function () {
        return view('administrator/dashboard/dashboard');  
    });
    
    Route::resource('/barang', 'barangController');
    Route::get('barang/tambah/stok', 'barangController@addStock')->name('add.stok');
    Route::post('barang/tambah/stok', 'barangController@storeStock')->name('barang.stok.store');
    Route::resource('/gudang', 'gudangController');
    Route::resource('/transaksi', 'transaksiController');
    Route::resource('/cart', 'CartController');
    Route::resource('/laporan', 'laporanController');
    Route::post('cart/add', 'CartController@add')->name('cart.add');
    Route::post('cart/remove', 'CartController@remove')->name('cart.remove');

    Route::get('/transaksi/print/{invoice}', 'transaksiController@generatePDF')->name('invoice.print');
    
    Route::get('/pelanggan', function () {
        return view('administrator/pelanggan');  
    });
});

Route::get('/home', 'HomeController@index')->name('home');

app/Transaksi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    protected $table = 'transactions';
    
    protected $fillable = ['invoice', 'name','phone','address',
                           'qty','amount'
                        ];
    public function getTanggalAttribute()
    {
        return \Carbon\Carbon::parse($this->attributes['date'])
            ->format('d, M Y H:i');
    }

    public function transaksi_details()
    {
        return $this->hasMany(TransaksiDetails::class, 'transaction_id','id');
    }
}

app/Http/Controllers/transaksiController.php
<?php

namespace App\Http\Controllers;

use PDF;
use App\Barang;
use App\Transaksi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class transaksiController extends Controller
{
        /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transaksis = Transaksi::orderBy('created_at','DESC')->paginate(10);
        return view('administrator.transaksi.index',compact('transaksis'));
    }  

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrator.transaksi.create');
    }

        /**
     * Store Transaksi to database.
     *
     * @param \App\Http\Requests\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $request->validate([
           'date' => ['required', 'date', 'date_format:Y-m-d H:i'],
           'partnumber' => ['required','numeric','min:0'],
           'name' => ['required', 'string', 'max:200'],
           'phone' => ['required', 'numeric', 'min:10'],
           'address' => 'sometimes',
           'qty' => 'required|numeric|min:1',
           'discount_one' => ['sometimes', 'nullable', 'numeric','min:0'],
           'discount_two' => ['sometimes', 'nullable', 'numeric','min:0'],
       ]);

       $barang = Product::where('partnumber',$request->partnumber)->firstOrFail();
       if($barang->stok<$request->qty){
        return redirect()->route('transaksi.create')->with('notification.error', trans('Stok tidak Mencukupi.'));
       }else{
            DB::transaction(function () use ($request) {
                /** @var \App\Transaksi $transaksi */
                $barang = Barang::where('partnumber',$request->partnumber)->firstOrFail();
                $transaksi = Transaksi::create([
                    'invoice' => $barang->getInvoice(),
                    'partnumber_id' => $request->partnumber,
                    'name' => $request->name,
                    'phone' => $request->phone,
                    'address' => $request->address,
                    'qty' => $request->qty,
                    'date' => $request->date,
                    'discount_one' => $request->discount_one,
                    'discount_two' => $request->discount_two,
                    'discounted_price' => $barang->getDiscounted_price($request->discount_one,$request->discount_two),
                    'amount' => $barang->getDiscounted_price($request->discount_one,$request->discount_two) * $request->qty
                ]);
                $barang->update(['stok' => $barang->stok-$request->qty]);
                return $transaksi;
            });
            return redirect()->route('transaksi.index');    
       }
       
    }

    /**
     * Show the form.
     *
     * @param  $partnumber
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $transaksi = Transaksi::where('id',$id)->firstOrfail();
        return view('administrator.transaksi.show', compact('transaksi'));
    }

    public function generatePDF($invoice)
    {
        
        $transaksi = Transaksi::where('invoice',$invoice)->firstOrfail();
        $pdf = PDF::loadView('administrator.transaksi.invoice', compact('transaksi'))->setPaper('a4','landscape');
        return $pdf->stream();

    }
    
}

resources/views/administrator/transaksi/create.blade.php
@extends('administrator.header')

@section('isi')
@include('administrator.transaksi.flash-message')
<div class="container" style="padding-top:25px;">  
  <button class="btn btn-warning" onclick="history.back();"><i class="fa fa-arrow-left"></i> Back</button> <br><br> 
  <form action="{{route('cart.add')}}" method="post">
      {{ csrf_field() }}
        {{-- <div class="form-group">
            <label for="date">Tanggal Pembelian</label>
            <input type="text" class="form-control datepicker-here" data-timepicker="true" id="date" name="date" placeholder="Tanggal Pembelian" required>
        </div> --}}
        <div class="form-group">
            <label for="partnumber">Part Number</label>
            <input type="text" class="form-control" id="partnumber" name="partnumber" placeholder="Part Number" required>
        </div>
        <div class="form-group">
            <label for="qty">QTY</label>
            <input type="number" class="form-control" id="qty" name='qty' min="0" placeholder="QTY">
        </div>
        <div class="form-row">
            <div class="form-group col-sm-6">
                <label for="discount_one">Potongan Pertama</label>
                <input type="number" class="form-control" min="0" id="discount_one" name="discount_one" placeholder="Potongan Pertama">
            </div>
            <div class="form-group col-sm-6">
                <label for="discount_two">Potongan Kedua</label>
                <input type="number" class="form-control" min="0" data-timepicker="true" id="discount_two" name="discount_two" placeholder="Potongan Kedua">
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Tambah ke Keranjang</button>
        <a href="{{route('cart.index')}}" class="btn btn-success">Lihat Keranjang</a>
  </form>
</div>
@endsection

@push('css')
<link rel="stylesheet" href="{{ asset('datepicker/css/datepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/easy-autocomplete.min.css') }}">
@endpush

@push('script')
<script src="{{ asset('datepicker/js/datepicker.js') }}"></script>
<script src="{{ asset('datepicker/js/datepicker.en.js') }}"></script>
<script src="{{asset('js/jquery.easy-autocomplete.min.js')}}"></script>
<script>
        $('#partnumber').easyAutocomplete({
            data: @json(App\Product::all('id', 'partnumber')),
            getValue: 'partnumber',
            list: {
                match: { enabled: true },
                maxNumberOfElements: 5,
                onChooseEvent: function () {
                    var selected = $('#partnumber').getSelectedItemData()
                    $('#partnumber').val(selected.partnumber);
                }
            },
        });
$(document).ready(function () {
    $('#date').datepicker({
        language: "en",
        autoClose: true,
        dateFormat: 'yyyy-mm-dd',
        timeformat: 'hh:ii',
    });
    // $('#discount').maskMoney({thousands:'.', decimal:',', precision:0});
    // $('#max_discount').maskMoney({thousands:'.', decimal:',', precision:0,allowZero:true});
    
});
</script>
@endpush

resources/views/administrator/transaksi/flash-message.blade.php
@if(Session::has('notification.error'))
<div style="position:absolute; z-index: 10020; margin-top: 5px; right: 25px;">
  
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        <i class="fas fa-lg fa-exclamation-circle mr-2"></i>
        {!! \Session::get('notification.error') !!}
        <button style="padding-left:10px" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>
@elseif(Session::has('notification.success'))
<div style="position:absolute; z-index: 10020; margin-top: 5px; right: 25px;">
  
    <div class="alert alert-success alert-dismissable fade show" role="alert">
        <i class="fas fa-lg fa-exclamation-circle mr-2"></i>
        {!! \Session::get('notification.success') !!}
        <button style="padding-left:10px" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>
 @endif

<script>
window.setTimeout(function() {
    $("div.alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 2500);
</script>

resources/views/administrator/transaksi/index.blade.php
@extends('administrator.header')
@section('isi')
@include('administrator.barang.flash-message')
<div class="container" style="padding-top:25px;">
    <div class="card">
        <div class="card-body">
          <h5 class="card-title">Transaksi
            <form method="get" action="" enctype="multipart/form-data">
              <div class="mb-3 form-inline" style="float:right"> 
                  <div class="form-group">
                      <div class="input-group">
                          <input type="text" name="search" class="form-control" placeholder="Cari Transaksi">
                          <div class="input-group-append">
                              <button type="submit" class="btn btn-secondary shadow-none">Cari</button>
                          </div>
                      </div>
                  </div>
              </div>
              </form>
          </h5>
          <table class="table table-striped table-bordered">
            <thead>
              <tr class="text-center">
                <th scope="col">Kode Transaksi</th>
                <th scope="col">Nama Pembeli</th>
                <th scope="col">Tanggal Pembelian</th>
                <th scope="col">Total</th>
                <th scope="col" width="100px">Action</th>
              </tr>
            </thead>
              @foreach ($transaksis->sortByDesc('created_at') as $trans)
              <tr class="text-center">
                <td>{{$trans->invoice}}</td>
                <td>{{$trans->name}}</td>
                <td>{{date('d, M Y H:i' , strtotime($trans->created_at))}}</td>
                <td>{{number_format($trans->amount,0,',','.')}}</td>
                <td>
                      <a role="button" href="{{ route('transaksi.show', $trans->id) }}" class="btn btn-sm btn-icon" data-toggle="tooltip" title="Lihat">
                        <i class="material-icons-outlined">visibility</i>
                      </a>
                      <form action="{{ route('transaksi.destroy', $trans->id) }}" method="POST" class="d-inline" onsubmit="return confirm('Are you sure delete?');">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        {{-- <button class="btn btn-sm btn-icon text-muted" data-toggle="tooltip" title="Delete">
                          <i class="material-icons-outlined">delete</i>
                      </button> --}}
                      </form>
                </td>
              </tr>
              @endforeach
            </tbody>
            <tfoot>
              <tr>
                  <td colspan="100">{{ $transaksis->links('administrator.pagination.pagination') }}</td>
              </tr>
          </tfoot>
          </table>
        </div>
      </div>
</div>
@endsection

resources/views/administrator/transaksi/invoice.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Invoice</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body{
            font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            color:#333;
            text-align:left;
            font-size:12px;
            margin:0;
        }
        table{
            border:1px solid #333;
            border-collapse:collapse;
        }
        td, tr, th{
            border:1px solid #333;
        }
        h4, p{
            margin:0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <table>
            <thead>
                <tr>
                    <td colspan="6"><h2 style="margin-bottom:0px;margin-top:0px;">CV. RIDHO JAYA</h2><p>Jl. Sungai Kahayan No.73 RT.18 Tanah Patah Bengkulu</p></td>
                    <th>#{{$transaksi->invoice}}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="6">
                        <table style="margin-top:15px;margin-bottom:15px;">
                            <tr>
                                <td width="225px">No INVOICE</td>
                                <td width="305px">{{$transaksi->invoice}}</td>
                            </tr>
                            <tr>
                                <td width="225px">NAMA TOKO</td>
                                <td width="305px">{{$transaksi->name}}</td>
                            </tr>
                            <tr>
                                <td width="225px">ALAMAT</td>
                                <td width="305px">{{$transaksi->address}}</td>
                            </tr>
                            <tr>
                                <td width="225px">TGL KIRIM BARANG</td>
                                <td width="305px">{{date('d, M Y' , strtotime($transaksi->created_at))}}</td>
                            </tr>
                            <tr>
                                <td width="225px">TGL JATUH TEMPO</td>
                                <td width="305px"></td>
                            </tr>

                       
                        </table>
                    </td>
                    <td></td>
                </tr>
                <tr class="text-center">
                    <th scope="col">Ukuran</th>
                    <th scope="col" width="150px">Pattern</th>
                    <th scope="col">QTY</th>
                    <th scope="col" width="100px">Harga Het</th>
                    <th scope="col" width="100px">Disc</th>
                    <th scope="col">Harga Set Discount</th>
                    <th scope="col">Total</th>
                  </tr>
                @foreach ($transaksi->transaksi_details as $item)
                <tr class="text-center">
                    <td>{{$item->product->ukuran}}</td>
                    <td>{{$item->product->pattern}}</td>
                    <td>{{$item->qty}}</td>
                    <td>{{'Rp '.number_format($item->product->het,0,',','.')}}</td>
                    @if($item->discount_one==null &&$item->discount_two==null)
                    <td>{{' '}}</td>
                    @elseif($item->discount_one!=null &&$item->discount_two==null)
                    <td>{{$item->discount_one.'%'}}</td>
                    @elseif($item->discount_one==null &&$item->discount_two!=null)
                    <td>{{$item->discount_two.'%'}}</td>
                    @elseif($item->discount_one!=null &&$item->discount_two!=null)
                    <td>{{$item->discount_one.'% +'.$item->discount_two.'%'}}</td>
                    @endif
                    <td>{{'Rp '.number_format($item->discounted_price,0,',','.')}}</td>
                    <td>{{'Rp '.number_format($item->amount,0,',','.')}}</td>
                </tr>
                 <tr>
                    <td colspan="5" style="border-left-style:hidden;border-bottom-style:hidden;border-right-style:hidden;">&nbsp;</td>
                    <td style="border-left-style:hidden;border-bottom-style:hidden;">Total</td>
                    <td>{{'Rp '.number_format($transaksi->amount,0,',','.')}}</td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6" style="border-top-style:hidden;">
                        <table>
                            <tr>
                                <td width="300px">YANG MENERIMA BARANG</td>
                                <td width="230px">CV.RIDHO JAYA</td>
                            </tr>
                            <tr>
                                <td height="50px"></td>
                                <td height="50px"></td>
                            </tr>
                        </table>
                    </td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
    </div>
</body>
</html>

resources/views/administrator/transaksi/show.blade.php
@extends('administrator.header')
@section('isi')
@include('administrator.barang.flash-message')
<div class="container" style="padding-top:25px;">
    <button class="btn btn-warning" onclick="history.back();"><i class="fa fa-arrow-left"></i> Back</button> <br><br> 
    <div class="card">
        <div class="card-body">
          <h5 class="card-title">Detail Pembeli
            <a href="{{route('invoice.print',$transaksi->invoice)}}" target="_blank" class="btn btn-success btn-sm float-right"><i class="material-icons" style="font-size:25px;display:inline-block;">print</i><strong>Print</strong></a>
          </h5>
          <table class="table table-striped table-bordered">
            <thead>
              <tr class="text-center">
                <th scope="col">Kode Transaksi</th>
                <th scope="col">Nama Pembeli</th>
                <th scope="col">Alamat Pembeli</th>
                <th scope="col">Tanggal Pembelian</th>
              </tr>
            </thead>
              <tr class="text-center">
                <td>{{$transaksi->invoice}}</td>
                <td>{{$transaksi->name}}</td>
                <td>{{$transaksi->address}}</td>
                <td>{{date('d, M Y H:i' , strtotime($transaksi->created_at))}}</td>
                </td>
              </tr> 
            </tbody>
          </table>

          <h5 class="card-title" style="padding-top:25px;">Detail Transaksi</h5>
          <table class="table table-striped table-bordered">
            <thead>
              <tr class="text-center">
                <th scope="col">Part Number</th>
                <th scope="col">Pattern</th>
                <th scope="col">Ukuran</th>
                <th scope="col">QTY</th>
                <th scope="col">Harga Het</th>
                <th scope="col" width="100px">Disc</th>
                <th scope="col">Harga Set Discount</th>
                <th scope="col">Total</th>
              </tr>
            </thead>
            @foreach($transaksi->transaksi_details as $item)
               <tr class="text-center">
                <td>{{$item->partnumber}}</td>
                <td>{{$item->product->pattern}}</td>
                <td>{{$item->product->ukuran}}</td>
                <td>{{$item->qty}}</td>
                <td>{{number_format($item->product->het,0,',','.')}}</td>
                @if($item->discount_one==null &&$item->discount_two==null)
                  <td>{{' '}}</td>
                @elseif($item->discount_one!=null &&$item->discount_two==null)
                  <td>{{$item->discount_one.'%'}}</td>
                @elseif($item->discount_one==null &&$item->discount_two!=null)
                  <td>{{$item->discount_two.'%'}}</td>
                  @elseif($item->discount_one!=null &&$item->discount_two!=null)
                  <td>{{$item->discount_one.'% +'.$item->discount_two.'%'}}</td>
                @endif
                <td>{{number_format($item->discounted_price,0,',','.')}}</td>
                <td>{{number_format($item->amount,0,',','.')}}</td>
              </tr>
              @endforeach()
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5" style="border-left-style:hidden;border-bottom-style:hidden;border-right-style:hidden;">&nbsp;</td>
                    <td style="border-left-style:hidden;border-bottom-style:hidden;">Total</td>
                    <td>{{number_format($transaksi->amount,0,',','.')}}</td>
                </tr>
            </tfoot>
          </table>
        </div>
      </div>
</div>
@endsection